version: '2.0'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - commander_DB:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd


volumes:

  commander_DB:
    driver: local